{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Barefoot Nomad",
    "description": "Make company global travel and accommodation easy and convenient ",
    "contact": {}
  },
  "basePath": "/api",
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/auth/signup": {
      "post": {
        "summary": "Signup",
        "tags": [
          "User"
        ],
        "operationId": "Signup",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SignupRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/auth/confirmation/{emailToken}": {
      "post": {
        "summary": "Confirm Email",
        "tags": [
          "User"
        ],
        "operationId": "ConfirmEmail",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "emailToken",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Logging In",
        "tags": [
          "User"
        ],
        "operationId": "LoggingIn",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/LoggingInRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/profile": {
      "get": {
        "summary": "View User Profile",
        "tags": [
          "Profile"
        ],
        "operationId": "ViewUserProfile",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "patch": {
        "summary": "Edit User Profile",
        "tags": [
          "Profile"
        ],
        "operationId": "EditUserProfile",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "image",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "first_name",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "last_name",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/auth/forget": {
      "post": {
        "summary": "Forget Password",
        "tags": [
          "User"
        ],
        "operationId": "ForgetPassword",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ForgetPasswordRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/auth/reset/{email}/{password}": {
      "patch": {
        "summary": "Reset User Password",
        "tags": [
          "User"
        ],
        "operationId": "ResetUserPassword",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "email",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "password",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ResetUserPasswordRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/auth/assignRole": {
      "patch": {
        "summary": "Assign User Roles",
        "tags": [
          "User"
        ],
        "operationId": "AssignUserRoles",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/AssignUserRolesRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/auth/logout": {
      "get": {
        "summary": "Logout",
        "tags": [
          "User"
        ],
        "operationId": "Logout",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/accommodations": {
      "post": {
        "summary": "Create accommodations",
        "tags": [
          "Accommodations"
        ],
        "operationId": "Createaccommodations",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "name",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "address",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "description",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "image",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "geoLocation",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "rooms",
            "in": "formData",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "services",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "amenities",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "get": {
        "summary": "Get all accommodation",
        "tags": [
          "Accommodations"
        ],
        "operationId": "Getallaccommodation",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/accommodations/{accommodation_id}/room": {
      "post": {
        "summary": "Add room request",
        "tags": [
          "Accommodations"
        ],
        "operationId": "Addroomrequest",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "accommodation_id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "description",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "geoLocation",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "amenities",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "image",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "type",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "area",
            "in": "formData",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "totalBedrooms",
            "in": "formData",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "roomNumber",
            "in": "formData",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "cost",
            "in": "formData",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/accommodations/{id}": {
      "get": {
        "summary": "View a single accommodation",
        "tags": [
          "Accommodations"
        ],
        "operationId": "Viewasingleaccommodation",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/accommodations/{id}/approve": {
      "patch": {
        "summary": "Approve an accommodation",
        "tags": [
          "Accommodations"
        ],
        "operationId": "Approveanaccommodation",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/accommodations/{id}/feedback": {
      "post": {
        "summary": "Feedback on Accommodation",
        "tags": [
          "Accommodations"
        ],
        "operationId": "FeedbackonAccommodation",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/FeedbackonAccommodationRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/accommodations/{id}/rate": {
      "post": {
        "summary": "Rating Accommodation",
        "tags": [
          "Accommodations"
        ],
        "operationId": "RatingAccommodation",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RatingAccommodationRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests/one_way": {
      "post": {
        "summary": "Request a one way trip",
        "tags": [
          "Trip"
        ],
        "operationId": "Requestaonewaytrip",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RequestaonewaytripRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests/return_trip": {
      "post": {
        "summary": "Request a return trip",
        "tags": [
          "Trip"
        ],
        "operationId": "Requestareturntrip",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RequestareturntripRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/accommodations/{accommodation_id}/book/{room_id}": {
      "post": {
        "summary": "Booking a room request",
        "tags": [
          "Accommodations"
        ],
        "operationId": "Bookingaroomrequest",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "accommodation_id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "room_id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/BookingaroomrequestRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests/{id}/edit": {
      "patch": {
        "summary": "Edit Travel request",
        "tags": [
          "Trip"
        ],
        "operationId": "EditTravelrequest",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/EditTravelrequestRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests/{id}/approve": {
      "patch": {
        "summary": "Aprove requests",
        "tags": [
          "Trip"
        ],
        "operationId": "Aproverequests",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/request/{id}/reject": {
      "patch": {
        "summary": "Reject request",
        "tags": [
          "Trip"
        ],
        "operationId": "Rejectrequest",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests": {
      "get": {
        "summary": "Get all requests by the requester",
        "tags": [
          "Trip"
        ],
        "operationId": "Getallrequestsbytherequester",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests/{id}/comment": {
      "post": {
        "summary": "Comment on request",
        "tags": [
          "Trip"
        ],
        "operationId": "Commentonrequest",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CommentonrequestRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests/{id}/comments": {
      "get": {
        "summary": "Get all comments",
        "tags": [
          "Trip"
        ],
        "operationId": "Getallcomments",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests/comment/{id}": {
      "delete": {
        "summary": "Delete a comment",
        "tags": [
          "Trip"
        ],
        "operationId": "Deleteacomment",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests/search": {
      "get": {
        "summary": "Search functionality",
        "tags": [
          "Trip"
        ],
        "operationId": "Searchfunctionality",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "keyword",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests/statistics": {
      "get": {
        "summary": "Get Trip Statistics",
        "tags": [
          "Trip"
        ],
        "operationId": "GetTripStatistics",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/requests/destinations/mostTravelled": {
      "get": {
        "summary": "Most travelled destination",
        "tags": [
          "Trip"
        ],
        "operationId": "Mosttravelleddestination",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/notifications/preferences": {
      "patch": {
        "summary": "Set Notification Preference",
        "tags": [
          "Notifications"
        ],
        "operationId": "SetNotificationPreference",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SetNotificationPreferenceRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/notifications/status/{value}": {
      "get": {
        "summary": "See Notification Status ( Either Read or Unread )",
        "tags": [
          "Notifications"
        ],
        "operationId": "SeeNotificationStatus(EitherReadorUnread)",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "value",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/notifications": {
      "get": {
        "summary": "Get all Notifications",
        "tags": [
          "Notifications"
        ],
        "operationId": "GetallNotifications",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "patch": {
        "summary": "Mark all notifications as Read",
        "tags": [
          "Notifications"
        ],
        "operationId": "MarkallnotificationsasRead",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/notifications/{id}": {
      "get": {
        "summary": "Get single Notifications",
        "tags": [
          "Notifications"
        ],
        "operationId": "GetsingleNotifications",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/notifications/{id}/read": {
      "patch": {
        "summary": "Mark a single notification as Read",
        "tags": [
          "Notifications"
        ],
        "operationId": "MarkasinglenotificationasRead",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/notifications/{id}/unread": {
      "patch": {
        "summary": "Mark a single notification as Unread",
        "tags": [
          "Notifications"
        ],
        "operationId": "MarkasinglenotificationasUnread",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "token",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/chat/": {
      "get": {
        "summary": "Chat bot",
        "tags": [
          "Chat"
        ],
        "operationId": "Chat",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "SignupRequest": {
      "title": "SignupRequest",
      "example": {
        "email": "sharonuase@gmail.com",
        "userName": "copain",
        "password": "Skemc1234"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "userName": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "userName",
        "password"
      ]
    },
    "LoggingInRequest": {
      "title": "LoggingInRequest",
      "example": {
        "email": "sharonuase@gmail.com",
        "password": "Skemc1234"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ]
    },
    "ForgetPasswordRequest": {
      "title": "ForgetPasswordRequest",
      "example": {
        "email": "eric.mico6@gmail.com"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        }
      },
      "required": [
        "email"
      ]
    },
    "ResetUserPasswordRequest": {
      "title": "ResetUserPasswordRequest",
      "example": {
        "password": "Skemc12345",
        "confirmPassword": "Skemc12345"
      },
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        },
        "confirmPassword": {
          "type": "string"
        }
      },
      "required": [
        "password",
        "confirmPassword"
      ]
    },
    "AssignUserRolesRequest": {
      "title": "AssignUserRolesRequest",
      "example": {
        "email": "bienaime.fabrice@andela.com",
        "role": "requester"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "role"
      ]
    },
    "FeedbackonAccommodationRequest": {
      "title": "FeedbackonAccommodationRequest",
      "example": {
        "feedback": "Update wifi"
      },
      "type": "object",
      "properties": {
        "feedback": {
          "type": "string"
        }
      },
      "required": [
        "feedback"
      ]
    },
    "RatingAccommodationRequest": {
      "title": "RatingAccommodationRequest",
      "example": {
        "rating": "3"
      },
      "type": "object",
      "properties": {
        "rating": {
          "type": "string"
        }
      },
      "required": [
        "rating"
      ]
    },
    "RequestaonewaytripRequest": {
      "title": "RequestaonewaytripRequest",
      "example": {
        "origin": "nigeria, lagos",
        "destination": "burundi, bujumbura",
        "travelDate": "2020-10-01",
        "reason": "business",
        "accommodationId": 1,
        "user_id": 1,
        "dob": "2020-10-01",
        "passportName": "bihire jules boris",
        "passportNumber": "232450",
        "gender": "Male",
        "rememberMe": true
      },
      "type": "object",
      "properties": {
        "origin": {
          "type": "string"
        },
        "destination": {
          "type": "string"
        },
        "travelDate": {
          "type": "string"
        },
        "reason": {
          "type": "string"
        },
        "accommodationId": {
          "type": "integer",
          "format": "int32"
        },
        "user_id": {
          "type": "integer",
          "format": "int32"
        },
        "dob": {
          "type": "string"
        },
        "passportName": {
          "type": "string"
        },
        "passportNumber": {
          "type": "string"
        },
        "gender": {
          "type": "string"
        },
        "rememberMe": {
          "type": "boolean"
        }
      },
      "required": [
        "origin",
        "destination",
        "travelDate",
        "reason",
        "accommodationId",
        "user_id",
        "dob",
        "passportName",
        "passportNumber",
        "gender",
        "rememberMe"
      ]
    },
    "RequestareturntripRequest": {
      "title": "RequestareturntripRequest",
      "example": {
        "origin": "nigeria, lagos",
        "destination": "burundi, bujumbura",
        "travelDate": "2020-10-01",
        "reason": "business",
        "accommodationId": 1,
        "user_id": 1,
        "returnDate": "2020-11-01",
        "dob": "2020-10-01",
        "passportName": "bihire jules boris",
        "passportNumber": 232450,
        "gender": "Male",
        "rememberMe": true
      },
      "type": "object",
      "properties": {
        "origin": {
          "type": "string"
        },
        "destination": {
          "type": "string"
        },
        "travelDate": {
          "type": "string"
        },
        "reason": {
          "type": "string"
        },
        "accommodationId": {
          "type": "integer",
          "format": "int32"
        },
        "user_id": {
          "type": "integer",
          "format": "int32"
        },
        "returnDate": {
          "type": "string"
        },
        "dob": {
          "type": "string"
        },
        "passportName": {
          "type": "string"
        },
        "passportNumber": {
          "type": "integer",
          "format": "int32"
        },
        "gender": {
          "type": "string"
        },
        "rememberMe": {
          "type": "boolean"
        }
      },
      "required": [
        "origin",
        "destination",
        "travelDate",
        "reason",
        "accommodationId",
        "user_id",
        "returnDate",
        "dob",
        "passportName",
        "passportNumber",
        "gender",
        "rememberMe"
      ]
    },
    "BookingaroomrequestRequest": {
      "title": "BookingaroomrequestRequest",
      "example": {
        "trip_id": 1,
        "room_id": 2,
        "accommodation_id": 1,
        "checkin": "2020-06-09",
        "checkout": "2020-08-06"
      },
      "type": "object",
      "properties": {
        "trip_id": {
          "type": "integer",
          "format": "int32"
        },
        "room_id": {
          "type": "integer",
          "format": "int32"
        },
        "accommodation_id": {
          "type": "integer",
          "format": "int32"
        },
        "checkin": {
          "type": "string"
        },
        "checkout": {
          "type": "string"
        }
      },
      "required": [
        "trip_id",
        "room_id",
        "accommodation_id",
        "checkin",
        "checkout"
      ]
    },
    "EditTravelrequestRequest": {
      "title": "EditTravelrequestRequest",
      "example": {
        "reason": "Family vacation"
      },
      "type": "object",
      "properties": {
        "reason": {
          "type": "string"
        }
      },
      "required": [
        "reason"
      ]
    },
    "CommentonrequestRequest": {
      "title": "CommentonrequestRequest",
      "example": {
        "comment": "thank you for joining"
      },
      "type": "object",
      "properties": {
        "comment": {
          "type": "string"
        }
      },
      "required": [
        "comment"
      ]
    },
    "SetNotificationPreferenceRequest": {
      "title": "SetNotificationPreferenceRequest",
      "example": {
        "emailNotification": "true"
      },
      "type": "object",
      "properties": {
        "emailNotification": {
          "type": "string"
        }
      },
      "required": [
        "emailNotification"
      ]
    }
  }
}